services:
  human3r:
    build: .
    command: tail -f
    runtime: nvidia
    volumes:
      - ./Human3R:/workspace
      - /usr/local/cuda:/usr/local/cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
